// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatMessageHandle : RemoteTableHandle<EventContext, ChatMessage>
        {
            protected override string RemoteTableName => "chat_message";

            public sealed class MessageIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatMessage row) => row.MessageId;

                public MessageIdUniqueIndex(ChatMessageHandle table) : base(table) { }
            }

            public readonly MessageIdUniqueIndex MessageId;

            internal ChatMessageHandle(DbConnection conn) : base(conn)
            {
                MessageId = new(this);
            }

            protected override object GetPrimaryKey(ChatMessage row) => row.MessageId;
        }

        public readonly ChatMessageHandle ChatMessage;
    }

    public sealed class ChatMessageCols
    {
        public global::SpacetimeDB.Col<ChatMessage, ulong> MessageId { get; }
        public global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Identity> Sender { get; }
        public global::SpacetimeDB.Col<ChatMessage, string> SenderName { get; }
        public global::SpacetimeDB.Col<ChatMessage, string> Content { get; }
        public global::SpacetimeDB.Col<ChatMessage, int> Channel { get; }
        public global::SpacetimeDB.Col<ChatMessage, long> Timestamp { get; }

        public ChatMessageCols(string tableName)
        {
            MessageId = new global::SpacetimeDB.Col<ChatMessage, ulong>(tableName, "message_id");
            Sender = new global::SpacetimeDB.Col<ChatMessage, SpacetimeDB.Identity>(tableName, "sender");
            SenderName = new global::SpacetimeDB.Col<ChatMessage, string>(tableName, "sender_name");
            Content = new global::SpacetimeDB.Col<ChatMessage, string>(tableName, "content");
            Channel = new global::SpacetimeDB.Col<ChatMessage, int>(tableName, "channel");
            Timestamp = new global::SpacetimeDB.Col<ChatMessage, long>(tableName, "timestamp");
        }
    }

    public sealed class ChatMessageIxCols
    {
        public global::SpacetimeDB.IxCol<ChatMessage, ulong> MessageId { get; }

        public ChatMessageIxCols(string tableName)
        {
            MessageId = new global::SpacetimeDB.IxCol<ChatMessage, ulong>(tableName, "message_id");
        }
    }
}
