// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DamageEventHandle : RemoteEventTableHandle<EventContext, DamageEvent>
        {
            protected override string RemoteTableName => "damage_event";

            internal DamageEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly DamageEventHandle DamageEvent;
    }

    public sealed class DamageEventCols
    {
        public global::SpacetimeDB.Col<DamageEvent, SpacetimeDB.Identity> Attacker { get; }
        public global::SpacetimeDB.Col<DamageEvent, SpacetimeDB.Identity> Victim { get; }
        public global::SpacetimeDB.Col<DamageEvent, uint> MobId { get; }
        public global::SpacetimeDB.Col<DamageEvent, int> Damage { get; }
        public global::SpacetimeDB.Col<DamageEvent, bool> IsCrit { get; }
        public global::SpacetimeDB.Col<DamageEvent, float> PosX { get; }
        public global::SpacetimeDB.Col<DamageEvent, float> PosY { get; }

        public DamageEventCols(string tableName)
        {
            Attacker = new global::SpacetimeDB.Col<DamageEvent, SpacetimeDB.Identity>(tableName, "attacker");
            Victim = new global::SpacetimeDB.Col<DamageEvent, SpacetimeDB.Identity>(tableName, "victim");
            MobId = new global::SpacetimeDB.Col<DamageEvent, uint>(tableName, "mob_id");
            Damage = new global::SpacetimeDB.Col<DamageEvent, int>(tableName, "damage");
            IsCrit = new global::SpacetimeDB.Col<DamageEvent, bool>(tableName, "is_crit");
            PosX = new global::SpacetimeDB.Col<DamageEvent, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<DamageEvent, float>(tableName, "pos_y");
        }
    }

    public sealed class DamageEventIxCols
    {

        public DamageEventIxCols(string tableName)
        {
        }
    }
}
