// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EquipmentHandle : RemoteTableHandle<EventContext, Equipment>
        {
            protected override string RemoteTableName => "equipment";

            public sealed class OwnerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Equipment row) => row.Owner;

                public OwnerUniqueIndex(EquipmentHandle table) : base(table) { }
            }

            public readonly OwnerUniqueIndex Owner;

            internal EquipmentHandle(DbConnection conn) : base(conn)
            {
                Owner = new(this);
            }

            protected override object GetPrimaryKey(Equipment row) => row.Owner;
        }

        public readonly EquipmentHandle Equipment;
    }

    public sealed class EquipmentCols
    {
        public global::SpacetimeDB.Col<Equipment, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<Equipment, uint> WeaponSlotId { get; }
        public global::SpacetimeDB.Col<Equipment, uint> ArmorSlotId { get; }
        public global::SpacetimeDB.Col<Equipment, uint> HelmetSlotId { get; }

        public EquipmentCols(string tableName)
        {
            Owner = new global::SpacetimeDB.Col<Equipment, SpacetimeDB.Identity>(tableName, "owner");
            WeaponSlotId = new global::SpacetimeDB.Col<Equipment, uint>(tableName, "weapon_slot_id");
            ArmorSlotId = new global::SpacetimeDB.Col<Equipment, uint>(tableName, "armor_slot_id");
            HelmetSlotId = new global::SpacetimeDB.Col<Equipment, uint>(tableName, "helmet_slot_id");
        }
    }

    public sealed class EquipmentIxCols
    {
        public global::SpacetimeDB.IxCol<Equipment, SpacetimeDB.Identity> Owner { get; }

        public EquipmentIxCols(string tableName)
        {
            Owner = new global::SpacetimeDB.IxCol<Equipment, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
