// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameConfigHandle : RemoteTableHandle<EventContext, GameConfig>
        {
            protected override string RemoteTableName => "game_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(GameConfig row) => row.Id;

                public IdUniqueIndex(GameConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameConfig row) => row.Id;
        }

        public readonly GameConfigHandle GameConfig;
    }

    public sealed class GameConfigCols
    {
        public global::SpacetimeDB.Col<GameConfig, uint> Id { get; }
        public global::SpacetimeDB.Col<GameConfig, float> WorldMinX { get; }
        public global::SpacetimeDB.Col<GameConfig, float> WorldMinY { get; }
        public global::SpacetimeDB.Col<GameConfig, float> WorldMaxX { get; }
        public global::SpacetimeDB.Col<GameConfig, float> WorldMaxY { get; }
        public global::SpacetimeDB.Col<GameConfig, float> SpawnPointX { get; }
        public global::SpacetimeDB.Col<GameConfig, float> SpawnPointY { get; }
        public global::SpacetimeDB.Col<GameConfig, int> MaxPlayersPerWorld { get; }
        public global::SpacetimeDB.Col<GameConfig, int> TickRateMs { get; }

        public GameConfigCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GameConfig, uint>(tableName, "id");
            WorldMinX = new global::SpacetimeDB.Col<GameConfig, float>(tableName, "world_min_x");
            WorldMinY = new global::SpacetimeDB.Col<GameConfig, float>(tableName, "world_min_y");
            WorldMaxX = new global::SpacetimeDB.Col<GameConfig, float>(tableName, "world_max_x");
            WorldMaxY = new global::SpacetimeDB.Col<GameConfig, float>(tableName, "world_max_y");
            SpawnPointX = new global::SpacetimeDB.Col<GameConfig, float>(tableName, "spawn_point_x");
            SpawnPointY = new global::SpacetimeDB.Col<GameConfig, float>(tableName, "spawn_point_y");
            MaxPlayersPerWorld = new global::SpacetimeDB.Col<GameConfig, int>(tableName, "max_players_per_world");
            TickRateMs = new global::SpacetimeDB.Col<GameConfig, int>(tableName, "tick_rate_ms");
        }
    }

    public sealed class GameConfigIxCols
    {
        public global::SpacetimeDB.IxCol<GameConfig, uint> Id { get; }

        public GameConfigIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GameConfig, uint>(tableName, "id");
        }
    }
}
