// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InventorySlotHandle : RemoteTableHandle<EventContext, InventorySlot>
        {
            protected override string RemoteTableName => "inventory_slot";

            public sealed class ByOwnerIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(InventorySlot row) => row.Owner;

                public ByOwnerIndex(InventorySlotHandle table) : base(table) { }
            }

            public readonly ByOwnerIndex ByOwner;

            public sealed class SlotIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(InventorySlot row) => row.SlotId;

                public SlotIdUniqueIndex(InventorySlotHandle table) : base(table) { }
            }

            public readonly SlotIdUniqueIndex SlotId;

            internal InventorySlotHandle(DbConnection conn) : base(conn)
            {
                ByOwner = new(this);
                SlotId = new(this);
            }

            protected override object GetPrimaryKey(InventorySlot row) => row.SlotId;
        }

        public readonly InventorySlotHandle InventorySlot;
    }

    public sealed class InventorySlotCols
    {
        public global::SpacetimeDB.Col<InventorySlot, uint> SlotId { get; }
        public global::SpacetimeDB.Col<InventorySlot, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<InventorySlot, uint> ItemId { get; }
        public global::SpacetimeDB.Col<InventorySlot, int> Quantity { get; }
        public global::SpacetimeDB.Col<InventorySlot, int> SlotIndex { get; }

        public InventorySlotCols(string tableName)
        {
            SlotId = new global::SpacetimeDB.Col<InventorySlot, uint>(tableName, "slot_id");
            Owner = new global::SpacetimeDB.Col<InventorySlot, SpacetimeDB.Identity>(tableName, "owner");
            ItemId = new global::SpacetimeDB.Col<InventorySlot, uint>(tableName, "item_id");
            Quantity = new global::SpacetimeDB.Col<InventorySlot, int>(tableName, "quantity");
            SlotIndex = new global::SpacetimeDB.Col<InventorySlot, int>(tableName, "slot_index");
        }
    }

    public sealed class InventorySlotIxCols
    {
        public global::SpacetimeDB.IxCol<InventorySlot, uint> SlotId { get; }
        public global::SpacetimeDB.IxCol<InventorySlot, SpacetimeDB.Identity> Owner { get; }

        public InventorySlotIxCols(string tableName)
        {
            SlotId = new global::SpacetimeDB.IxCol<InventorySlot, uint>(tableName, "slot_id");
            Owner = new global::SpacetimeDB.IxCol<InventorySlot, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
