// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ItemDefHandle : RemoteTableHandle<EventContext, ItemDef>
        {
            protected override string RemoteTableName => "item_def";

            public sealed class ItemIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ItemDef row) => row.ItemId;

                public ItemIdUniqueIndex(ItemDefHandle table) : base(table) { }
            }

            public readonly ItemIdUniqueIndex ItemId;

            internal ItemDefHandle(DbConnection conn) : base(conn)
            {
                ItemId = new(this);
            }

            protected override object GetPrimaryKey(ItemDef row) => row.ItemId;
        }

        public readonly ItemDefHandle ItemDef;
    }

    public sealed class ItemDefCols
    {
        public global::SpacetimeDB.Col<ItemDef, uint> ItemId { get; }
        public global::SpacetimeDB.Col<ItemDef, string> Name { get; }
        public global::SpacetimeDB.Col<ItemDef, string> Description { get; }
        public global::SpacetimeDB.Col<ItemDef, int> ItemType { get; }
        public global::SpacetimeDB.Col<ItemDef, int> Rarity { get; }
        public global::SpacetimeDB.Col<ItemDef, int> SpriteIndex { get; }
        public global::SpacetimeDB.Col<ItemDef, int> BonusAtk { get; }
        public global::SpacetimeDB.Col<ItemDef, int> BonusDef { get; }
        public global::SpacetimeDB.Col<ItemDef, int> BonusHp { get; }
        public global::SpacetimeDB.Col<ItemDef, int> BonusMp { get; }
        public global::SpacetimeDB.Col<ItemDef, int> BonusSpeed { get; }
        public global::SpacetimeDB.Col<ItemDef, bool> Stackable { get; }
        public global::SpacetimeDB.Col<ItemDef, int> MaxStack { get; }

        public ItemDefCols(string tableName)
        {
            ItemId = new global::SpacetimeDB.Col<ItemDef, uint>(tableName, "item_id");
            Name = new global::SpacetimeDB.Col<ItemDef, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<ItemDef, string>(tableName, "description");
            ItemType = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "item_type");
            Rarity = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "rarity");
            SpriteIndex = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "sprite_index");
            BonusAtk = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "bonus_atk");
            BonusDef = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "bonus_def");
            BonusHp = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "bonus_hp");
            BonusMp = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "bonus_mp");
            BonusSpeed = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "bonus_speed");
            Stackable = new global::SpacetimeDB.Col<ItemDef, bool>(tableName, "stackable");
            MaxStack = new global::SpacetimeDB.Col<ItemDef, int>(tableName, "max_stack");
        }
    }

    public sealed class ItemDefIxCols
    {
        public global::SpacetimeDB.IxCol<ItemDef, uint> ItemId { get; }

        public ItemDefIxCols(string tableName)
        {
            ItemId = new global::SpacetimeDB.IxCol<ItemDef, uint>(tableName, "item_id");
        }
    }
}
