// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LootDropHandle : RemoteTableHandle<EventContext, LootDrop>
        {
            protected override string RemoteTableName => "loot_drop";

            public sealed class DropIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(LootDrop row) => row.DropId;

                public DropIdUniqueIndex(LootDropHandle table) : base(table) { }
            }

            public readonly DropIdUniqueIndex DropId;

            internal LootDropHandle(DbConnection conn) : base(conn)
            {
                DropId = new(this);
            }

            protected override object GetPrimaryKey(LootDrop row) => row.DropId;
        }

        public readonly LootDropHandle LootDrop;
    }

    public sealed class LootDropCols
    {
        public global::SpacetimeDB.Col<LootDrop, uint> DropId { get; }
        public global::SpacetimeDB.Col<LootDrop, uint> ItemId { get; }
        public global::SpacetimeDB.Col<LootDrop, int> Quantity { get; }
        public global::SpacetimeDB.Col<LootDrop, float> PosX { get; }
        public global::SpacetimeDB.Col<LootDrop, float> PosY { get; }
        public global::SpacetimeDB.Col<LootDrop, long> DroppedAt { get; }

        public LootDropCols(string tableName)
        {
            DropId = new global::SpacetimeDB.Col<LootDrop, uint>(tableName, "drop_id");
            ItemId = new global::SpacetimeDB.Col<LootDrop, uint>(tableName, "item_id");
            Quantity = new global::SpacetimeDB.Col<LootDrop, int>(tableName, "quantity");
            PosX = new global::SpacetimeDB.Col<LootDrop, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<LootDrop, float>(tableName, "pos_y");
            DroppedAt = new global::SpacetimeDB.Col<LootDrop, long>(tableName, "dropped_at");
        }
    }

    public sealed class LootDropIxCols
    {
        public global::SpacetimeDB.IxCol<LootDrop, uint> DropId { get; }

        public LootDropIxCols(string tableName)
        {
            DropId = new global::SpacetimeDB.IxCol<LootDrop, uint>(tableName, "drop_id");
        }
    }
}
