// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MobDefHandle : RemoteTableHandle<EventContext, MobDef>
        {
            protected override string RemoteTableName => "mob_def";

            public sealed class MobDefIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MobDef row) => row.MobDefId;

                public MobDefIdUniqueIndex(MobDefHandle table) : base(table) { }
            }

            public readonly MobDefIdUniqueIndex MobDefId;

            internal MobDefHandle(DbConnection conn) : base(conn)
            {
                MobDefId = new(this);
            }

            protected override object GetPrimaryKey(MobDef row) => row.MobDefId;
        }

        public readonly MobDefHandle MobDef;
    }

    public sealed class MobDefCols
    {
        public global::SpacetimeDB.Col<MobDef, uint> MobDefId { get; }
        public global::SpacetimeDB.Col<MobDef, string> Name { get; }
        public global::SpacetimeDB.Col<MobDef, int> SpritePresetIndex { get; }
        public global::SpacetimeDB.Col<MobDef, int> MaxHp { get; }
        public global::SpacetimeDB.Col<MobDef, int> Atk { get; }
        public global::SpacetimeDB.Col<MobDef, int> Def { get; }
        public global::SpacetimeDB.Col<MobDef, float> Speed { get; }
        public global::SpacetimeDB.Col<MobDef, float> AggroRange { get; }
        public global::SpacetimeDB.Col<MobDef, float> AttackRange { get; }
        public global::SpacetimeDB.Col<MobDef, int> ExpReward { get; }
        public global::SpacetimeDB.Col<MobDef, string> LootTableJson { get; }

        public MobDefCols(string tableName)
        {
            MobDefId = new global::SpacetimeDB.Col<MobDef, uint>(tableName, "mob_def_id");
            Name = new global::SpacetimeDB.Col<MobDef, string>(tableName, "name");
            SpritePresetIndex = new global::SpacetimeDB.Col<MobDef, int>(tableName, "sprite_preset_index");
            MaxHp = new global::SpacetimeDB.Col<MobDef, int>(tableName, "max_hp");
            Atk = new global::SpacetimeDB.Col<MobDef, int>(tableName, "atk");
            Def = new global::SpacetimeDB.Col<MobDef, int>(tableName, "def");
            Speed = new global::SpacetimeDB.Col<MobDef, float>(tableName, "speed");
            AggroRange = new global::SpacetimeDB.Col<MobDef, float>(tableName, "aggro_range");
            AttackRange = new global::SpacetimeDB.Col<MobDef, float>(tableName, "attack_range");
            ExpReward = new global::SpacetimeDB.Col<MobDef, int>(tableName, "exp_reward");
            LootTableJson = new global::SpacetimeDB.Col<MobDef, string>(tableName, "loot_table_json");
        }
    }

    public sealed class MobDefIxCols
    {
        public global::SpacetimeDB.IxCol<MobDef, uint> MobDefId { get; }

        public MobDefIxCols(string tableName)
        {
            MobDefId = new global::SpacetimeDB.IxCol<MobDef, uint>(tableName, "mob_def_id");
        }
    }
}
