// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MobInstanceHandle : RemoteTableHandle<EventContext, MobInstance>
        {
            protected override string RemoteTableName => "mob_instance";

            public sealed class MobIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MobInstance row) => row.MobId;

                public MobIdUniqueIndex(MobInstanceHandle table) : base(table) { }
            }

            public readonly MobIdUniqueIndex MobId;

            internal MobInstanceHandle(DbConnection conn) : base(conn)
            {
                MobId = new(this);
            }

            protected override object GetPrimaryKey(MobInstance row) => row.MobId;
        }

        public readonly MobInstanceHandle MobInstance;
    }

    public sealed class MobInstanceCols
    {
        public global::SpacetimeDB.Col<MobInstance, uint> MobId { get; }
        public global::SpacetimeDB.Col<MobInstance, uint> MobDefId { get; }
        public global::SpacetimeDB.Col<MobInstance, float> PosX { get; }
        public global::SpacetimeDB.Col<MobInstance, float> PosY { get; }
        public global::SpacetimeDB.Col<MobInstance, float> SpawnX { get; }
        public global::SpacetimeDB.Col<MobInstance, float> SpawnY { get; }
        public global::SpacetimeDB.Col<MobInstance, int> CurrentHp { get; }
        public global::SpacetimeDB.Col<MobInstance, int> AiState { get; }
        public global::SpacetimeDB.Col<MobInstance, SpacetimeDB.Identity> TargetPlayer { get; }
        public global::SpacetimeDB.Col<MobInstance, float> DirX { get; }
        public global::SpacetimeDB.Col<MobInstance, float> DirY { get; }
        public global::SpacetimeDB.Col<MobInstance, int> AnimState { get; }
        public global::SpacetimeDB.Col<MobInstance, bool> FacingRight { get; }
        public global::SpacetimeDB.Col<MobInstance, long> DeadAtMs { get; }

        public MobInstanceCols(string tableName)
        {
            MobId = new global::SpacetimeDB.Col<MobInstance, uint>(tableName, "mob_id");
            MobDefId = new global::SpacetimeDB.Col<MobInstance, uint>(tableName, "mob_def_id");
            PosX = new global::SpacetimeDB.Col<MobInstance, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<MobInstance, float>(tableName, "pos_y");
            SpawnX = new global::SpacetimeDB.Col<MobInstance, float>(tableName, "spawn_x");
            SpawnY = new global::SpacetimeDB.Col<MobInstance, float>(tableName, "spawn_y");
            CurrentHp = new global::SpacetimeDB.Col<MobInstance, int>(tableName, "current_hp");
            AiState = new global::SpacetimeDB.Col<MobInstance, int>(tableName, "ai_state");
            TargetPlayer = new global::SpacetimeDB.Col<MobInstance, SpacetimeDB.Identity>(tableName, "target_player");
            DirX = new global::SpacetimeDB.Col<MobInstance, float>(tableName, "dir_x");
            DirY = new global::SpacetimeDB.Col<MobInstance, float>(tableName, "dir_y");
            AnimState = new global::SpacetimeDB.Col<MobInstance, int>(tableName, "anim_state");
            FacingRight = new global::SpacetimeDB.Col<MobInstance, bool>(tableName, "facing_right");
            DeadAtMs = new global::SpacetimeDB.Col<MobInstance, long>(tableName, "dead_at_ms");
        }
    }

    public sealed class MobInstanceIxCols
    {
        public global::SpacetimeDB.IxCol<MobInstance, uint> MobId { get; }

        public MobInstanceIxCols(string tableName)
        {
            MobId = new global::SpacetimeDB.IxCol<MobInstance, uint>(tableName, "mob_id");
        }
    }
}
