// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerAppearanceHandle : RemoteTableHandle<EventContext, PlayerAppearance>
        {
            protected override string RemoteTableName => "player_appearance";

            public sealed class OwnerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerAppearance row) => row.Owner;

                public OwnerUniqueIndex(PlayerAppearanceHandle table) : base(table) { }
            }

            public readonly OwnerUniqueIndex Owner;

            internal PlayerAppearanceHandle(DbConnection conn) : base(conn)
            {
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PlayerAppearance row) => row.Owner;
        }

        public readonly PlayerAppearanceHandle PlayerAppearance;
    }

    public sealed class PlayerAppearanceCols
    {
        public global::SpacetimeDB.Col<PlayerAppearance, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Skin { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Eyes { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Brow { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Mouth { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> HairShort { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> HairHat { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Beard { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Top { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Bottom { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Boots { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Gloves { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Helmet { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Eyewear { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> GearLeft { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> GearRight { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> Back { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> SkinColor { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> HairColor { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> BeardColor { get; }
        public global::SpacetimeDB.Col<PlayerAppearance, int> BrowColor { get; }

        public PlayerAppearanceCols(string tableName)
        {
            Owner = new global::SpacetimeDB.Col<PlayerAppearance, SpacetimeDB.Identity>(tableName, "owner");
            Skin = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "skin");
            Eyes = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "eyes");
            Brow = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "brow");
            Mouth = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "mouth");
            HairShort = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "hair_short");
            HairHat = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "hair_hat");
            Beard = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "beard");
            Top = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "top");
            Bottom = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "bottom");
            Boots = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "boots");
            Gloves = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "gloves");
            Helmet = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "helmet");
            Eyewear = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "eyewear");
            GearLeft = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "gear_left");
            GearRight = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "gear_right");
            Back = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "back");
            SkinColor = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "skin_color");
            HairColor = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "hair_color");
            BeardColor = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "beard_color");
            BrowColor = new global::SpacetimeDB.Col<PlayerAppearance, int>(tableName, "brow_color");
        }
    }

    public sealed class PlayerAppearanceIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerAppearance, SpacetimeDB.Identity> Owner { get; }

        public PlayerAppearanceIxCols(string tableName)
        {
            Owner = new global::SpacetimeDB.IxCol<PlayerAppearance, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
