// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerPositionHandle : RemoteTableHandle<EventContext, PlayerPosition>
        {
            protected override string RemoteTableName => "player_position";

            public sealed class OwnerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerPosition row) => row.Owner;

                public OwnerUniqueIndex(PlayerPositionHandle table) : base(table) { }
            }

            public readonly OwnerUniqueIndex Owner;

            internal PlayerPositionHandle(DbConnection conn) : base(conn)
            {
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PlayerPosition row) => row.Owner;
        }

        public readonly PlayerPositionHandle PlayerPosition;
    }

    public sealed class PlayerPositionCols
    {
        public global::SpacetimeDB.Col<PlayerPosition, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> PosX { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> PosY { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> DirX { get; }
        public global::SpacetimeDB.Col<PlayerPosition, float> DirY { get; }
        public global::SpacetimeDB.Col<PlayerPosition, int> AnimState { get; }
        public global::SpacetimeDB.Col<PlayerPosition, bool> FacingRight { get; }

        public PlayerPositionCols(string tableName)
        {
            Owner = new global::SpacetimeDB.Col<PlayerPosition, SpacetimeDB.Identity>(tableName, "owner");
            PosX = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "pos_x");
            PosY = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "pos_y");
            DirX = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "dir_x");
            DirY = new global::SpacetimeDB.Col<PlayerPosition, float>(tableName, "dir_y");
            AnimState = new global::SpacetimeDB.Col<PlayerPosition, int>(tableName, "anim_state");
            FacingRight = new global::SpacetimeDB.Col<PlayerPosition, bool>(tableName, "facing_right");
        }
    }

    public sealed class PlayerPositionIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerPosition, SpacetimeDB.Identity> Owner { get; }

        public PlayerPositionIxCols(string tableName)
        {
            Owner = new global::SpacetimeDB.IxCol<PlayerPosition, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
