// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "player";

            public sealed class OwnerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Owner;

                public OwnerUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly OwnerUniqueIndex Owner;

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Player row) => row.Username;

                public UsernameUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                Owner = new(this);
                Username = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Owner;
        }

        public readonly PlayerHandle Player;
    }

    public sealed class PlayerCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<Player, string> Username { get; }
        public global::SpacetimeDB.Col<Player, bool> IsOnline { get; }
        public global::SpacetimeDB.Col<Player, bool> IsAdmin { get; }
        public global::SpacetimeDB.Col<Player, long> CreatedAt { get; }
        public global::SpacetimeDB.Col<Player, long> LastLogin { get; }

        public PlayerCols(string tableName)
        {
            Owner = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "owner");
            Username = new global::SpacetimeDB.Col<Player, string>(tableName, "username");
            IsOnline = new global::SpacetimeDB.Col<Player, bool>(tableName, "is_online");
            IsAdmin = new global::SpacetimeDB.Col<Player, bool>(tableName, "is_admin");
            CreatedAt = new global::SpacetimeDB.Col<Player, long>(tableName, "created_at");
            LastLogin = new global::SpacetimeDB.Col<Player, long>(tableName, "last_login");
        }
    }

    public sealed class PlayerIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.IxCol<Player, string> Username { get; }

        public PlayerIxCols(string tableName)
        {
            Owner = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "owner");
            Username = new global::SpacetimeDB.IxCol<Player, string>(tableName, "username");
        }
    }
}
