// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerStatsHandle : RemoteTableHandle<EventContext, PlayerStats>
        {
            protected override string RemoteTableName => "player_stats";

            public sealed class OwnerUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerStats row) => row.Owner;

                public OwnerUniqueIndex(PlayerStatsHandle table) : base(table) { }
            }

            public readonly OwnerUniqueIndex Owner;

            internal PlayerStatsHandle(DbConnection conn) : base(conn)
            {
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PlayerStats row) => row.Owner;
        }

        public readonly PlayerStatsHandle PlayerStats;
    }

    public sealed class PlayerStatsCols
    {
        public global::SpacetimeDB.Col<PlayerStats, SpacetimeDB.Identity> Owner { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Level { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Exp { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> MaxHp { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> CurrentHp { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> MaxMp { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> CurrentMp { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Atk { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> Def { get; }
        public global::SpacetimeDB.Col<PlayerStats, float> Speed { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> TotalKills { get; }
        public global::SpacetimeDB.Col<PlayerStats, int> TotalDeaths { get; }

        public PlayerStatsCols(string tableName)
        {
            Owner = new global::SpacetimeDB.Col<PlayerStats, SpacetimeDB.Identity>(tableName, "owner");
            Level = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "level");
            Exp = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "exp");
            MaxHp = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "max_hp");
            CurrentHp = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "current_hp");
            MaxMp = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "max_mp");
            CurrentMp = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "current_mp");
            Atk = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "atk");
            Def = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "def");
            Speed = new global::SpacetimeDB.Col<PlayerStats, float>(tableName, "speed");
            TotalKills = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "total_kills");
            TotalDeaths = new global::SpacetimeDB.Col<PlayerStats, int>(tableName, "total_deaths");
        }
    }

    public sealed class PlayerStatsIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerStats, SpacetimeDB.Identity> Owner { get; }

        public PlayerStatsIxCols(string tableName)
        {
            Owner = new global::SpacetimeDB.IxCol<PlayerStats, SpacetimeDB.Identity>(tableName, "owner");
        }
    }
}
