// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SpawnConfigHandle : RemoteTableHandle<EventContext, SpawnConfig>
        {
            protected override string RemoteTableName => "spawn_config";

            public sealed class ConfigIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(SpawnConfig row) => row.ConfigId;

                public ConfigIdUniqueIndex(SpawnConfigHandle table) : base(table) { }
            }

            public readonly ConfigIdUniqueIndex ConfigId;

            internal SpawnConfigHandle(DbConnection conn) : base(conn)
            {
                ConfigId = new(this);
            }

            protected override object GetPrimaryKey(SpawnConfig row) => row.ConfigId;
        }

        public readonly SpawnConfigHandle SpawnConfig;
    }

    public sealed class SpawnConfigCols
    {
        public global::SpacetimeDB.Col<SpawnConfig, uint> ConfigId { get; }
        public global::SpacetimeDB.Col<SpawnConfig, uint> MobDefId { get; }
        public global::SpacetimeDB.Col<SpawnConfig, float> ZoneMinX { get; }
        public global::SpacetimeDB.Col<SpawnConfig, float> ZoneMinY { get; }
        public global::SpacetimeDB.Col<SpawnConfig, float> ZoneMaxX { get; }
        public global::SpacetimeDB.Col<SpawnConfig, float> ZoneMaxY { get; }
        public global::SpacetimeDB.Col<SpawnConfig, int> MaxCount { get; }
        public global::SpacetimeDB.Col<SpawnConfig, int> RespawnTimeSec { get; }
        public global::SpacetimeDB.Col<SpawnConfig, bool> IsActive { get; }

        public SpawnConfigCols(string tableName)
        {
            ConfigId = new global::SpacetimeDB.Col<SpawnConfig, uint>(tableName, "config_id");
            MobDefId = new global::SpacetimeDB.Col<SpawnConfig, uint>(tableName, "mob_def_id");
            ZoneMinX = new global::SpacetimeDB.Col<SpawnConfig, float>(tableName, "zone_min_x");
            ZoneMinY = new global::SpacetimeDB.Col<SpawnConfig, float>(tableName, "zone_min_y");
            ZoneMaxX = new global::SpacetimeDB.Col<SpawnConfig, float>(tableName, "zone_max_x");
            ZoneMaxY = new global::SpacetimeDB.Col<SpawnConfig, float>(tableName, "zone_max_y");
            MaxCount = new global::SpacetimeDB.Col<SpawnConfig, int>(tableName, "max_count");
            RespawnTimeSec = new global::SpacetimeDB.Col<SpawnConfig, int>(tableName, "respawn_time_sec");
            IsActive = new global::SpacetimeDB.Col<SpawnConfig, bool>(tableName, "is_active");
        }
    }

    public sealed class SpawnConfigIxCols
    {
        public global::SpacetimeDB.IxCol<SpawnConfig, uint> ConfigId { get; }

        public SpawnConfigIxCols(string tableName)
        {
            ConfigId = new global::SpacetimeDB.IxCol<SpawnConfig, uint>(tableName, "config_id");
        }
    }
}
