// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminTeleportHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetPlayer, float x, float y);
        public event AdminTeleportHandler? OnAdminTeleport;

        public void AdminTeleport(SpacetimeDB.Identity targetPlayer, float x, float y)
        {
            conn.InternalCallReducer(new Reducer.AdminTeleport(targetPlayer, x, y));
        }

        public bool InvokeAdminTeleport(ReducerEventContext ctx, Reducer.AdminTeleport args)
        {
            if (OnAdminTeleport == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminTeleport(
                ctx,
                args.TargetPlayer,
                args.X,
                args.Y
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminTeleport : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_player")]
            public SpacetimeDB.Identity TargetPlayer;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;

            public AdminTeleport(
                SpacetimeDB.Identity TargetPlayer,
                float X,
                float Y
            )
            {
                this.TargetPlayer = TargetPlayer;
                this.X = X;
                this.Y = Y;
            }

            public AdminTeleport()
            {
            }

            string IReducerArgs.ReducerName => "admin_teleport";
        }
    }
}
