// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminSpawnMobHandler(ReducerEventContext ctx, uint mobDefId, float x, float y, int count);
        public event AdminSpawnMobHandler? OnAdminSpawnMob;

        public void AdminSpawnMob(uint mobDefId, float x, float y, int count)
        {
            conn.InternalCallReducer(new Reducer.AdminSpawnMob(mobDefId, x, y, count));
        }

        public bool InvokeAdminSpawnMob(ReducerEventContext ctx, Reducer.AdminSpawnMob args)
        {
            if (OnAdminSpawnMob == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminSpawnMob(
                ctx,
                args.MobDefId,
                args.X,
                args.Y,
                args.Count
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminSpawnMob : Reducer, IReducerArgs
        {
            [DataMember(Name = "mob_def_id")]
            public uint MobDefId;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;
            [DataMember(Name = "count")]
            public int Count;

            public AdminSpawnMob(
                uint MobDefId,
                float X,
                float Y,
                int Count
            )
            {
                this.MobDefId = MobDefId;
                this.X = X;
                this.Y = Y;
                this.Count = Count;
            }

            public AdminSpawnMob()
            {
            }

            string IReducerArgs.ReducerName => "admin_spawn_mob";
        }
    }
}
