// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminSpawnRandomWaveHandler(ReducerEventContext ctx, int totalCount, float centerX, float centerY, float radius);
        public event AdminSpawnRandomWaveHandler? OnAdminSpawnRandomWave;

        public void AdminSpawnRandomWave(int totalCount, float centerX, float centerY, float radius)
        {
            conn.InternalCallReducer(new Reducer.AdminSpawnRandomWave(totalCount, centerX, centerY, radius));
        }

        public bool InvokeAdminSpawnRandomWave(ReducerEventContext ctx, Reducer.AdminSpawnRandomWave args)
        {
            if (OnAdminSpawnRandomWave == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminSpawnRandomWave(
                ctx,
                args.TotalCount,
                args.CenterX,
                args.CenterY,
                args.Radius
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminSpawnRandomWave : Reducer, IReducerArgs
        {
            [DataMember(Name = "total_count")]
            public int TotalCount;
            [DataMember(Name = "center_x")]
            public float CenterX;
            [DataMember(Name = "center_y")]
            public float CenterY;
            [DataMember(Name = "radius")]
            public float Radius;

            public AdminSpawnRandomWave(
                int TotalCount,
                float CenterX,
                float CenterY,
                float Radius
            )
            {
                this.TotalCount = TotalCount;
                this.CenterX = CenterX;
                this.CenterY = CenterY;
                this.Radius = Radius;
            }

            public AdminSpawnRandomWave()
            {
            }

            string IReducerArgs.ReducerName => "admin_spawn_random_wave";
        }
    }
}
