// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminSetStatsHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetPlayer, int hp, int mp, int atk, int def);
        public event AdminSetStatsHandler? OnAdminSetStats;

        public void AdminSetStats(SpacetimeDB.Identity targetPlayer, int hp, int mp, int atk, int def)
        {
            conn.InternalCallReducer(new Reducer.AdminSetStats(targetPlayer, hp, mp, atk, def));
        }

        public bool InvokeAdminSetStats(ReducerEventContext ctx, Reducer.AdminSetStats args)
        {
            if (OnAdminSetStats == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminSetStats(
                ctx,
                args.TargetPlayer,
                args.Hp,
                args.Mp,
                args.Atk,
                args.Def
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminSetStats : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_player")]
            public SpacetimeDB.Identity TargetPlayer;
            [DataMember(Name = "hp")]
            public int Hp;
            [DataMember(Name = "mp")]
            public int Mp;
            [DataMember(Name = "atk")]
            public int Atk;
            [DataMember(Name = "def")]
            public int Def;

            public AdminSetStats(
                SpacetimeDB.Identity TargetPlayer,
                int Hp,
                int Mp,
                int Atk,
                int Def
            )
            {
                this.TargetPlayer = TargetPlayer;
                this.Hp = Hp;
                this.Mp = Mp;
                this.Atk = Atk;
                this.Def = Def;
            }

            public AdminSetStats()
            {
            }

            string IReducerArgs.ReducerName => "admin_set_stats";
        }
    }
}
