// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminGiveItemHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetPlayer, uint itemId, int quantity);
        public event AdminGiveItemHandler? OnAdminGiveItem;

        public void AdminGiveItem(SpacetimeDB.Identity targetPlayer, uint itemId, int quantity)
        {
            conn.InternalCallReducer(new Reducer.AdminGiveItem(targetPlayer, itemId, quantity));
        }

        public bool InvokeAdminGiveItem(ReducerEventContext ctx, Reducer.AdminGiveItem args)
        {
            if (OnAdminGiveItem == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminGiveItem(
                ctx,
                args.TargetPlayer,
                args.ItemId,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminGiveItem : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_player")]
            public SpacetimeDB.Identity TargetPlayer;
            [DataMember(Name = "item_id")]
            public uint ItemId;
            [DataMember(Name = "quantity")]
            public int Quantity;

            public AdminGiveItem(
                SpacetimeDB.Identity TargetPlayer,
                uint ItemId,
                int Quantity
            )
            {
                this.TargetPlayer = TargetPlayer;
                this.ItemId = ItemId;
                this.Quantity = Quantity;
            }

            public AdminGiveItem()
            {
            }

            string IReducerArgs.ReducerName => "admin_give_item";
        }
    }
}
