// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminToggleSpawnConfigHandler(ReducerEventContext ctx, uint configId, bool isActive);
        public event AdminToggleSpawnConfigHandler? OnAdminToggleSpawnConfig;

        public void AdminToggleSpawnConfig(uint configId, bool isActive)
        {
            conn.InternalCallReducer(new Reducer.AdminToggleSpawnConfig(configId, isActive));
        }

        public bool InvokeAdminToggleSpawnConfig(ReducerEventContext ctx, Reducer.AdminToggleSpawnConfig args)
        {
            if (OnAdminToggleSpawnConfig == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminToggleSpawnConfig(
                ctx,
                args.ConfigId,
                args.IsActive
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminToggleSpawnConfig : Reducer, IReducerArgs
        {
            [DataMember(Name = "config_id")]
            public uint ConfigId;
            [DataMember(Name = "is_active")]
            public bool IsActive;

            public AdminToggleSpawnConfig(
                uint ConfigId,
                bool IsActive
            )
            {
                this.ConfigId = ConfigId;
                this.IsActive = IsActive;
            }

            public AdminToggleSpawnConfig()
            {
            }

            string IReducerArgs.ReducerName => "admin_toggle_spawn_config";
        }
    }
}
