// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminKillAllMobsHandler(ReducerEventContext ctx);
        public event AdminKillAllMobsHandler? OnAdminKillAllMobs;

        public void AdminKillAllMobs()
        {
            conn.InternalCallReducer(new Reducer.AdminKillAllMobs());
        }

        public bool InvokeAdminKillAllMobs(ReducerEventContext ctx, Reducer.AdminKillAllMobs args)
        {
            if (OnAdminKillAllMobs == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminKillAllMobs(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminKillAllMobs : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_kill_all_mobs";
        }
    }
}
