// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminHealAllPlayersHandler(ReducerEventContext ctx);
        public event AdminHealAllPlayersHandler? OnAdminHealAllPlayers;

        public void AdminHealAllPlayers()
        {
            conn.InternalCallReducer(new Reducer.AdminHealAllPlayers());
        }

        public bool InvokeAdminHealAllPlayers(ReducerEventContext ctx, Reducer.AdminHealAllPlayers args)
        {
            if (OnAdminHealAllPlayers == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminHealAllPlayers(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminHealAllPlayers : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_heal_all_players";
        }
    }
}
