// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AttackMobHandler(ReducerEventContext ctx, uint mobId);
        public event AttackMobHandler? OnAttackMob;

        public void AttackMob(uint mobId)
        {
            conn.InternalCallReducer(new Reducer.AttackMob(mobId));
        }

        public bool InvokeAttackMob(ReducerEventContext ctx, Reducer.AttackMob args)
        {
            if (OnAttackMob == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAttackMob(
                ctx,
                args.MobId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AttackMob : Reducer, IReducerArgs
        {
            [DataMember(Name = "mob_id")]
            public uint MobId;

            public AttackMob(uint MobId)
            {
                this.MobId = MobId;
            }

            public AttackMob()
            {
            }

            string IReducerArgs.ReducerName => "attack_mob";
        }
    }
}
