// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AttackPlayerHandler(ReducerEventContext ctx, SpacetimeDB.Identity targetId);
        public event AttackPlayerHandler? OnAttackPlayer;

        public void AttackPlayer(SpacetimeDB.Identity targetId)
        {
            conn.InternalCallReducer(new Reducer.AttackPlayer(targetId));
        }

        public bool InvokeAttackPlayer(ReducerEventContext ctx, Reducer.AttackPlayer args)
        {
            if (OnAttackPlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAttackPlayer(
                ctx,
                args.TargetId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AttackPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "target_id")]
            public SpacetimeDB.Identity TargetId;

            public AttackPlayer(SpacetimeDB.Identity TargetId)
            {
                this.TargetId = TargetId;
            }

            public AttackPlayer()
            {
            }

            string IReducerArgs.ReducerName => "attack_player";
        }
    }
}
