// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateCharacterHandler(ReducerEventContext ctx, string username, int skin, int eyes, int brow, int mouth, int hairShort, int beard, int top, int bottom, int boots, int skinColor, int hairColor, int beardColor, int browColor);
        public event CreateCharacterHandler? OnCreateCharacter;

        public void CreateCharacter(string username, int skin, int eyes, int brow, int mouth, int hairShort, int beard, int top, int bottom, int boots, int skinColor, int hairColor, int beardColor, int browColor)
        {
            conn.InternalCallReducer(new Reducer.CreateCharacter(username, skin, eyes, brow, mouth, hairShort, beard, top, bottom, boots, skinColor, hairColor, beardColor, browColor));
        }

        public bool InvokeCreateCharacter(ReducerEventContext ctx, Reducer.CreateCharacter args)
        {
            if (OnCreateCharacter == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCreateCharacter(
                ctx,
                args.Username,
                args.Skin,
                args.Eyes,
                args.Brow,
                args.Mouth,
                args.HairShort,
                args.Beard,
                args.Top,
                args.Bottom,
                args.Boots,
                args.SkinColor,
                args.HairColor,
                args.BeardColor,
                args.BrowColor
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateCharacter : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "skin")]
            public int Skin;
            [DataMember(Name = "eyes")]
            public int Eyes;
            [DataMember(Name = "brow")]
            public int Brow;
            [DataMember(Name = "mouth")]
            public int Mouth;
            [DataMember(Name = "hair_short")]
            public int HairShort;
            [DataMember(Name = "beard")]
            public int Beard;
            [DataMember(Name = "top")]
            public int Top;
            [DataMember(Name = "bottom")]
            public int Bottom;
            [DataMember(Name = "boots")]
            public int Boots;
            [DataMember(Name = "skin_color")]
            public int SkinColor;
            [DataMember(Name = "hair_color")]
            public int HairColor;
            [DataMember(Name = "beard_color")]
            public int BeardColor;
            [DataMember(Name = "brow_color")]
            public int BrowColor;

            public CreateCharacter(
                string Username,
                int Skin,
                int Eyes,
                int Brow,
                int Mouth,
                int HairShort,
                int Beard,
                int Top,
                int Bottom,
                int Boots,
                int SkinColor,
                int HairColor,
                int BeardColor,
                int BrowColor
            )
            {
                this.Username = Username;
                this.Skin = Skin;
                this.Eyes = Eyes;
                this.Brow = Brow;
                this.Mouth = Mouth;
                this.HairShort = HairShort;
                this.Beard = Beard;
                this.Top = Top;
                this.Bottom = Bottom;
                this.Boots = Boots;
                this.SkinColor = SkinColor;
                this.HairColor = HairColor;
                this.BeardColor = BeardColor;
                this.BrowColor = BrowColor;
            }

            public CreateCharacter()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "create_character";
        }
    }
}
