// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnterWorldHandler(ReducerEventContext ctx);
        public event EnterWorldHandler? OnEnterWorld;

        public void EnterWorld()
        {
            conn.InternalCallReducer(new Reducer.EnterWorld());
        }

        public bool InvokeEnterWorld(ReducerEventContext ctx, Reducer.EnterWorld args)
        {
            if (OnEnterWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnterWorld(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnterWorld : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "enter_world";
        }
    }
}
