// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PickupLootHandler(ReducerEventContext ctx, uint dropId);
        public event PickupLootHandler? OnPickupLoot;

        public void PickupLoot(uint dropId)
        {
            conn.InternalCallReducer(new Reducer.PickupLoot(dropId));
        }

        public bool InvokePickupLoot(ReducerEventContext ctx, Reducer.PickupLoot args)
        {
            if (OnPickupLoot == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPickupLoot(
                ctx,
                args.DropId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PickupLoot : Reducer, IReducerArgs
        {
            [DataMember(Name = "drop_id")]
            public uint DropId;

            public PickupLoot(uint DropId)
            {
                this.DropId = DropId;
            }

            public PickupLoot()
            {
            }

            string IReducerArgs.ReducerName => "pickup_loot";
        }
    }
}
