// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnMobHandler(ReducerEventContext ctx, uint mobDefId, float x, float y);
        public event SpawnMobHandler? OnSpawnMob;

        public void SpawnMob(uint mobDefId, float x, float y)
        {
            conn.InternalCallReducer(new Reducer.SpawnMob(mobDefId, x, y));
        }

        public bool InvokeSpawnMob(ReducerEventContext ctx, Reducer.SpawnMob args)
        {
            if (OnSpawnMob == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSpawnMob(
                ctx,
                args.MobDefId,
                args.X,
                args.Y
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnMob : Reducer, IReducerArgs
        {
            [DataMember(Name = "mob_def_id")]
            public uint MobDefId;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;

            public SpawnMob(
                uint MobDefId,
                float X,
                float Y
            )
            {
                this.MobDefId = MobDefId;
                this.X = X;
                this.Y = Y;
            }

            public SpawnMob()
            {
            }

            string IReducerArgs.ReducerName => "spawn_mob";
        }
    }
}
