// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateMovementHandler(ReducerEventContext ctx, float dirX, float dirY, int animState, bool facingRight);
        public event UpdateMovementHandler? OnUpdateMovement;

        public void UpdateMovement(float dirX, float dirY, int animState, bool facingRight)
        {
            conn.InternalCallReducer(new Reducer.UpdateMovement(dirX, dirY, animState, facingRight));
        }

        public bool InvokeUpdateMovement(ReducerEventContext ctx, Reducer.UpdateMovement args)
        {
            if (OnUpdateMovement == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateMovement(
                ctx,
                args.DirX,
                args.DirY,
                args.AnimState,
                args.FacingRight
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateMovement : Reducer, IReducerArgs
        {
            [DataMember(Name = "dir_x")]
            public float DirX;
            [DataMember(Name = "dir_y")]
            public float DirY;
            [DataMember(Name = "anim_state")]
            public int AnimState;
            [DataMember(Name = "facing_right")]
            public bool FacingRight;

            public UpdateMovement(
                float DirX,
                float DirY,
                int AnimState,
                bool FacingRight
            )
            {
                this.DirX = DirX;
                this.DirY = DirY;
                this.AnimState = AnimState;
                this.FacingRight = FacingRight;
            }

            public UpdateMovement()
            {
            }

            string IReducerArgs.ReducerName => "update_movement";
        }
    }
}
