// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UseSkillHandler(ReducerEventContext ctx, int skillId, float targetX, float targetY);
        public event UseSkillHandler? OnUseSkill;

        public void UseSkill(int skillId, float targetX, float targetY)
        {
            conn.InternalCallReducer(new Reducer.UseSkill(skillId, targetX, targetY));
        }

        public bool InvokeUseSkill(ReducerEventContext ctx, Reducer.UseSkill args)
        {
            if (OnUseSkill == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUseSkill(
                ctx,
                args.SkillId,
                args.TargetX,
                args.TargetY
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UseSkill : Reducer, IReducerArgs
        {
            [DataMember(Name = "skill_id")]
            public int SkillId;
            [DataMember(Name = "target_x")]
            public float TargetX;
            [DataMember(Name = "target_y")]
            public float TargetY;

            public UseSkill(
                int SkillId,
                float TargetX,
                float TargetY
            )
            {
                this.SkillId = SkillId;
                this.TargetX = TargetX;
                this.TargetY = TargetY;
            }

            public UseSkill()
            {
            }

            string IReducerArgs.ReducerName => "use_skill";
        }
    }
}
