// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChatMessage
    {
        [DataMember(Name = "message_id")]
        public ulong MessageId;
        [DataMember(Name = "sender")]
        public SpacetimeDB.Identity Sender;
        [DataMember(Name = "sender_name")]
        public string SenderName;
        [DataMember(Name = "content")]
        public string Content;
        [DataMember(Name = "channel")]
        public int Channel;
        [DataMember(Name = "timestamp")]
        public long Timestamp;

        public ChatMessage(
            ulong MessageId,
            SpacetimeDB.Identity Sender,
            string SenderName,
            string Content,
            int Channel,
            long Timestamp
        )
        {
            this.MessageId = MessageId;
            this.Sender = Sender;
            this.SenderName = SenderName;
            this.Content = Content;
            this.Channel = Channel;
            this.Timestamp = Timestamp;
        }

        public ChatMessage()
        {
            this.SenderName = "";
            this.Content = "";
        }
    }
}
