// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DamageEvent
    {
        [DataMember(Name = "attacker")]
        public SpacetimeDB.Identity Attacker;
        [DataMember(Name = "victim")]
        public SpacetimeDB.Identity Victim;
        [DataMember(Name = "mob_id")]
        public uint MobId;
        [DataMember(Name = "damage")]
        public int Damage;
        [DataMember(Name = "is_crit")]
        public bool IsCrit;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;

        public DamageEvent(
            SpacetimeDB.Identity Attacker,
            SpacetimeDB.Identity Victim,
            uint MobId,
            int Damage,
            bool IsCrit,
            float PosX,
            float PosY
        )
        {
            this.Attacker = Attacker;
            this.Victim = Victim;
            this.MobId = MobId;
            this.Damage = Damage;
            this.IsCrit = IsCrit;
            this.PosX = PosX;
            this.PosY = PosY;
        }

        public DamageEvent()
        {
        }
    }
}
