// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Equipment
    {
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "weapon_slot_id")]
        public uint WeaponSlotId;
        [DataMember(Name = "armor_slot_id")]
        public uint ArmorSlotId;
        [DataMember(Name = "helmet_slot_id")]
        public uint HelmetSlotId;

        public Equipment(
            SpacetimeDB.Identity Owner,
            uint WeaponSlotId,
            uint ArmorSlotId,
            uint HelmetSlotId
        )
        {
            this.Owner = Owner;
            this.WeaponSlotId = WeaponSlotId;
            this.ArmorSlotId = ArmorSlotId;
            this.HelmetSlotId = HelmetSlotId;
        }

        public Equipment()
        {
        }
    }
}
