// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameConfig
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "world_min_x")]
        public float WorldMinX;
        [DataMember(Name = "world_min_y")]
        public float WorldMinY;
        [DataMember(Name = "world_max_x")]
        public float WorldMaxX;
        [DataMember(Name = "world_max_y")]
        public float WorldMaxY;
        [DataMember(Name = "spawn_point_x")]
        public float SpawnPointX;
        [DataMember(Name = "spawn_point_y")]
        public float SpawnPointY;
        [DataMember(Name = "max_players_per_world")]
        public int MaxPlayersPerWorld;
        [DataMember(Name = "tick_rate_ms")]
        public int TickRateMs;

        public GameConfig(
            uint Id,
            float WorldMinX,
            float WorldMinY,
            float WorldMaxX,
            float WorldMaxY,
            float SpawnPointX,
            float SpawnPointY,
            int MaxPlayersPerWorld,
            int TickRateMs
        )
        {
            this.Id = Id;
            this.WorldMinX = WorldMinX;
            this.WorldMinY = WorldMinY;
            this.WorldMaxX = WorldMaxX;
            this.WorldMaxY = WorldMaxY;
            this.SpawnPointX = SpawnPointX;
            this.SpawnPointY = SpawnPointY;
            this.MaxPlayersPerWorld = MaxPlayersPerWorld;
            this.TickRateMs = TickRateMs;
        }

        public GameConfig()
        {
        }
    }
}
