// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InventorySlot
    {
        [DataMember(Name = "slot_id")]
        public uint SlotId;
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "item_id")]
        public uint ItemId;
        [DataMember(Name = "quantity")]
        public int Quantity;
        [DataMember(Name = "slot_index")]
        public int SlotIndex;

        public InventorySlot(
            uint SlotId,
            SpacetimeDB.Identity Owner,
            uint ItemId,
            int Quantity,
            int SlotIndex
        )
        {
            this.SlotId = SlotId;
            this.Owner = Owner;
            this.ItemId = ItemId;
            this.Quantity = Quantity;
            this.SlotIndex = SlotIndex;
        }

        public InventorySlot()
        {
        }
    }
}
