// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ItemDef
    {
        [DataMember(Name = "item_id")]
        public uint ItemId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "item_type")]
        public int ItemType;
        [DataMember(Name = "rarity")]
        public int Rarity;
        [DataMember(Name = "sprite_index")]
        public int SpriteIndex;
        [DataMember(Name = "bonus_atk")]
        public int BonusAtk;
        [DataMember(Name = "bonus_def")]
        public int BonusDef;
        [DataMember(Name = "bonus_hp")]
        public int BonusHp;
        [DataMember(Name = "bonus_mp")]
        public int BonusMp;
        [DataMember(Name = "bonus_speed")]
        public int BonusSpeed;
        [DataMember(Name = "stackable")]
        public bool Stackable;
        [DataMember(Name = "max_stack")]
        public int MaxStack;

        public ItemDef(
            uint ItemId,
            string Name,
            string Description,
            int ItemType,
            int Rarity,
            int SpriteIndex,
            int BonusAtk,
            int BonusDef,
            int BonusHp,
            int BonusMp,
            int BonusSpeed,
            bool Stackable,
            int MaxStack
        )
        {
            this.ItemId = ItemId;
            this.Name = Name;
            this.Description = Description;
            this.ItemType = ItemType;
            this.Rarity = Rarity;
            this.SpriteIndex = SpriteIndex;
            this.BonusAtk = BonusAtk;
            this.BonusDef = BonusDef;
            this.BonusHp = BonusHp;
            this.BonusMp = BonusMp;
            this.BonusSpeed = BonusSpeed;
            this.Stackable = Stackable;
            this.MaxStack = MaxStack;
        }

        public ItemDef()
        {
            this.Name = "";
            this.Description = "";
        }
    }
}
