// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class LootDrop
    {
        [DataMember(Name = "drop_id")]
        public uint DropId;
        [DataMember(Name = "item_id")]
        public uint ItemId;
        [DataMember(Name = "quantity")]
        public int Quantity;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "dropped_at")]
        public long DroppedAt;

        public LootDrop(
            uint DropId,
            uint ItemId,
            int Quantity,
            float PosX,
            float PosY,
            long DroppedAt
        )
        {
            this.DropId = DropId;
            this.ItemId = ItemId;
            this.Quantity = Quantity;
            this.PosX = PosX;
            this.PosY = PosY;
            this.DroppedAt = DroppedAt;
        }

        public LootDrop()
        {
        }
    }
}
