// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MobDef
    {
        [DataMember(Name = "mob_def_id")]
        public uint MobDefId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "sprite_preset_index")]
        public int SpritePresetIndex;
        [DataMember(Name = "max_hp")]
        public int MaxHp;
        [DataMember(Name = "atk")]
        public int Atk;
        [DataMember(Name = "def")]
        public int Def;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "aggro_range")]
        public float AggroRange;
        [DataMember(Name = "attack_range")]
        public float AttackRange;
        [DataMember(Name = "exp_reward")]
        public int ExpReward;
        [DataMember(Name = "loot_table_json")]
        public string LootTableJson;

        public MobDef(
            uint MobDefId,
            string Name,
            int SpritePresetIndex,
            int MaxHp,
            int Atk,
            int Def,
            float Speed,
            float AggroRange,
            float AttackRange,
            int ExpReward,
            string LootTableJson
        )
        {
            this.MobDefId = MobDefId;
            this.Name = Name;
            this.SpritePresetIndex = SpritePresetIndex;
            this.MaxHp = MaxHp;
            this.Atk = Atk;
            this.Def = Def;
            this.Speed = Speed;
            this.AggroRange = AggroRange;
            this.AttackRange = AttackRange;
            this.ExpReward = ExpReward;
            this.LootTableJson = LootTableJson;
        }

        public MobDef()
        {
            this.Name = "";
            this.LootTableJson = "";
        }
    }
}
