// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MobInstance
    {
        [DataMember(Name = "mob_id")]
        public uint MobId;
        [DataMember(Name = "mob_def_id")]
        public uint MobDefId;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "spawn_x")]
        public float SpawnX;
        [DataMember(Name = "spawn_y")]
        public float SpawnY;
        [DataMember(Name = "current_hp")]
        public int CurrentHp;
        [DataMember(Name = "ai_state")]
        public int AiState;
        [DataMember(Name = "target_player")]
        public SpacetimeDB.Identity TargetPlayer;
        [DataMember(Name = "dir_x")]
        public float DirX;
        [DataMember(Name = "dir_y")]
        public float DirY;
        [DataMember(Name = "anim_state")]
        public int AnimState;
        [DataMember(Name = "facing_right")]
        public bool FacingRight;
        [DataMember(Name = "dead_at_ms")]
        public long DeadAtMs;

        public MobInstance(
            uint MobId,
            uint MobDefId,
            float PosX,
            float PosY,
            float SpawnX,
            float SpawnY,
            int CurrentHp,
            int AiState,
            SpacetimeDB.Identity TargetPlayer,
            float DirX,
            float DirY,
            int AnimState,
            bool FacingRight,
            long DeadAtMs
        )
        {
            this.MobId = MobId;
            this.MobDefId = MobDefId;
            this.PosX = PosX;
            this.PosY = PosY;
            this.SpawnX = SpawnX;
            this.SpawnY = SpawnY;
            this.CurrentHp = CurrentHp;
            this.AiState = AiState;
            this.TargetPlayer = TargetPlayer;
            this.DirX = DirX;
            this.DirY = DirY;
            this.AnimState = AnimState;
            this.FacingRight = FacingRight;
            this.DeadAtMs = DeadAtMs;
        }

        public MobInstance()
        {
        }
    }
}
