// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerAppearance
    {
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "skin")]
        public int Skin;
        [DataMember(Name = "eyes")]
        public int Eyes;
        [DataMember(Name = "brow")]
        public int Brow;
        [DataMember(Name = "mouth")]
        public int Mouth;
        [DataMember(Name = "hair_short")]
        public int HairShort;
        [DataMember(Name = "hair_hat")]
        public int HairHat;
        [DataMember(Name = "beard")]
        public int Beard;
        [DataMember(Name = "top")]
        public int Top;
        [DataMember(Name = "bottom")]
        public int Bottom;
        [DataMember(Name = "boots")]
        public int Boots;
        [DataMember(Name = "gloves")]
        public int Gloves;
        [DataMember(Name = "helmet")]
        public int Helmet;
        [DataMember(Name = "eyewear")]
        public int Eyewear;
        [DataMember(Name = "gear_left")]
        public int GearLeft;
        [DataMember(Name = "gear_right")]
        public int GearRight;
        [DataMember(Name = "back")]
        public int Back;
        [DataMember(Name = "skin_color")]
        public int SkinColor;
        [DataMember(Name = "hair_color")]
        public int HairColor;
        [DataMember(Name = "beard_color")]
        public int BeardColor;
        [DataMember(Name = "brow_color")]
        public int BrowColor;

        public PlayerAppearance(
            SpacetimeDB.Identity Owner,
            int Skin,
            int Eyes,
            int Brow,
            int Mouth,
            int HairShort,
            int HairHat,
            int Beard,
            int Top,
            int Bottom,
            int Boots,
            int Gloves,
            int Helmet,
            int Eyewear,
            int GearLeft,
            int GearRight,
            int Back,
            int SkinColor,
            int HairColor,
            int BeardColor,
            int BrowColor
        )
        {
            this.Owner = Owner;
            this.Skin = Skin;
            this.Eyes = Eyes;
            this.Brow = Brow;
            this.Mouth = Mouth;
            this.HairShort = HairShort;
            this.HairHat = HairHat;
            this.Beard = Beard;
            this.Top = Top;
            this.Bottom = Bottom;
            this.Boots = Boots;
            this.Gloves = Gloves;
            this.Helmet = Helmet;
            this.Eyewear = Eyewear;
            this.GearLeft = GearLeft;
            this.GearRight = GearRight;
            this.Back = Back;
            this.SkinColor = SkinColor;
            this.HairColor = HairColor;
            this.BeardColor = BeardColor;
            this.BrowColor = BrowColor;
        }

        public PlayerAppearance()
        {
        }
    }
}
