// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerStats
    {
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "level")]
        public int Level;
        [DataMember(Name = "exp")]
        public int Exp;
        [DataMember(Name = "max_hp")]
        public int MaxHp;
        [DataMember(Name = "current_hp")]
        public int CurrentHp;
        [DataMember(Name = "max_mp")]
        public int MaxMp;
        [DataMember(Name = "current_mp")]
        public int CurrentMp;
        [DataMember(Name = "atk")]
        public int Atk;
        [DataMember(Name = "def")]
        public int Def;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "total_kills")]
        public int TotalKills;
        [DataMember(Name = "total_deaths")]
        public int TotalDeaths;

        public PlayerStats(
            SpacetimeDB.Identity Owner,
            int Level,
            int Exp,
            int MaxHp,
            int CurrentHp,
            int MaxMp,
            int CurrentMp,
            int Atk,
            int Def,
            float Speed,
            int TotalKills,
            int TotalDeaths
        )
        {
            this.Owner = Owner;
            this.Level = Level;
            this.Exp = Exp;
            this.MaxHp = MaxHp;
            this.CurrentHp = CurrentHp;
            this.MaxMp = MaxMp;
            this.CurrentMp = CurrentMp;
            this.Atk = Atk;
            this.Def = Def;
            this.Speed = Speed;
            this.TotalKills = TotalKills;
            this.TotalDeaths = TotalDeaths;
        }

        public PlayerStats()
        {
        }
    }
}
