// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "is_online")]
        public bool IsOnline;
        [DataMember(Name = "is_admin")]
        public bool IsAdmin;
        [DataMember(Name = "created_at")]
        public long CreatedAt;
        [DataMember(Name = "last_login")]
        public long LastLogin;

        public Player(
            SpacetimeDB.Identity Owner,
            string Username,
            bool IsOnline,
            bool IsAdmin,
            long CreatedAt,
            long LastLogin
        )
        {
            this.Owner = Owner;
            this.Username = Username;
            this.IsOnline = IsOnline;
            this.IsAdmin = IsAdmin;
            this.CreatedAt = CreatedAt;
            this.LastLogin = LastLogin;
        }

        public Player()
        {
            this.Username = "";
        }
    }
}
