// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerPosition
    {
        [DataMember(Name = "owner")]
        public SpacetimeDB.Identity Owner;
        [DataMember(Name = "pos_x")]
        public float PosX;
        [DataMember(Name = "pos_y")]
        public float PosY;
        [DataMember(Name = "dir_x")]
        public float DirX;
        [DataMember(Name = "dir_y")]
        public float DirY;
        [DataMember(Name = "anim_state")]
        public int AnimState;
        [DataMember(Name = "facing_right")]
        public bool FacingRight;

        public PlayerPosition(
            SpacetimeDB.Identity Owner,
            float PosX,
            float PosY,
            float DirX,
            float DirY,
            int AnimState,
            bool FacingRight
        )
        {
            this.Owner = Owner;
            this.PosX = PosX;
            this.PosY = PosY;
            this.DirX = DirX;
            this.DirY = DirY;
            this.AnimState = AnimState;
            this.FacingRight = FacingRight;
        }

        public PlayerPosition()
        {
        }
    }
}
