// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SpawnConfig
    {
        [DataMember(Name = "config_id")]
        public uint ConfigId;
        [DataMember(Name = "mob_def_id")]
        public uint MobDefId;
        [DataMember(Name = "zone_min_x")]
        public float ZoneMinX;
        [DataMember(Name = "zone_min_y")]
        public float ZoneMinY;
        [DataMember(Name = "zone_max_x")]
        public float ZoneMaxX;
        [DataMember(Name = "zone_max_y")]
        public float ZoneMaxY;
        [DataMember(Name = "max_count")]
        public int MaxCount;
        [DataMember(Name = "respawn_time_sec")]
        public int RespawnTimeSec;
        [DataMember(Name = "is_active")]
        public bool IsActive;

        public SpawnConfig(
            uint ConfigId,
            uint MobDefId,
            float ZoneMinX,
            float ZoneMinY,
            float ZoneMaxX,
            float ZoneMaxY,
            int MaxCount,
            int RespawnTimeSec,
            bool IsActive
        )
        {
            this.ConfigId = ConfigId;
            this.MobDefId = MobDefId;
            this.ZoneMinX = ZoneMinX;
            this.ZoneMinY = ZoneMinY;
            this.ZoneMaxX = ZoneMaxX;
            this.ZoneMaxY = ZoneMaxY;
            this.MaxCount = MaxCount;
            this.RespawnTimeSec = RespawnTimeSec;
            this.IsActive = IsActive;
        }

        public SpawnConfig()
        {
        }
    }
}
